---
name: "Manual Lint"
on: [push, pull_request]

jobs:
  lint:
    name: Manual Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install TinyCC
      run: sudo apt update && sudo apt -y install tcc

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/bld/pkg

    - name: Configure CMake
      run: >
        cmake -B "${{ runner.workspace }}/bld"
        -DCMAKE_C_COMPILER=tcc
        -DCMAKE_BUILD_TYPE=RelOnHost
        -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/bld/pkg

    - name: Build Fildesh
      run: |
        cmake --build "${{ runner.workspace }}/bld"
        cmake --install "${{ runner.workspace }}/bld" --component "bin"

    - name: Lint
      run: >
        ${{runner.workspace}}/bld/pkg/bin/fildesh
        test/manual/lint.fildesh
