---
name: Package

on:
  push:
    branches: [release, stage, trunk]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      run: >
        cmake -E make_directory
        ${{runner.workspace}}/bld/pkg/fildesh/DEBIAN
        ${{runner.workspace}}/bld/pkg/fildesh/usr
        ${{runner.workspace}}/bld/pkg/final

    - name: Configure CMake
      run: >
        cmake -B "${{ runner.workspace }}/bld"
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/bld/pkg/fildesh/usr

    - name: Build
      run: cmake --build "${{ runner.workspace }}/bld"

    - name: Install
      run: |
        cmake --install "${{ runner.workspace }}/bld" --component "bin"
        cmake --install "${{ runner.workspace }}/bld" --component "lib"
        cmake --install "${{ runner.workspace }}/bld" --component "share_vim"

    - name: Package deb
      working-directory: ${{runner.workspace}}
      run: >
        ./bld/pkg/fildesh/usr/bin/fildesh
        $GITHUB_WORKSPACE/pkg/debian/workflow_stage.fildesh
        --source_root=$GITHUB_WORKSPACE
        --pkg_dst=${{runner.workspace}}/bld/pkg

    - name: Package ebuild
      working-directory: ${{runner.workspace}}
      run: >
        ./bld/pkg/fildesh/usr/bin/fildesh
        $GITHUB_WORKSPACE/pkg/gentoo/workflow_stage.fildesh
        --source_root=$GITHUB_WORKSPACE
        --final_dst=${{runner.workspace}}/bld/pkg/final

    - name: Package source
      working-directory: ${{runner.workspace}}
      run: >
        ./bld/pkg/fildesh/usr/bin/fildesh
        $GITHUB_WORKSPACE/pkg/source/workflow_stage.fildesh
        --source_root=$GITHUB_WORKSPACE
        --final_dst=${{runner.workspace}}/bld/pkg/final

    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ${{runner.workspace}}/bld/pkg/final/
