---
on:
  push:
    branches:
      - "deploy"
env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"
jobs:
  build_and_push:
    steps:
      - name: "Bazel Setup"
        uses: "jwlawson/actions-setup-bazel@v2"
        with:
          bazel-version: "latest"
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - run: "bazel build -c opt //:fildesh"
        name: "Build"
      - name: "Docker Login"
        uses: "docker/login-action@v3"
        with:
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
      - name: "Build and Push Image"
        uses: "docker/build-push-action@v6"
        with:
          file: "pkg/docker/Dockerfile"
          push: true
          tags: "ghcr.io/fildesh/fildesh:latest"
          context: "bazel-bin/"
    runs-on: "ubuntu-20.04"
    permissions:
      contents: "read"
      packages: "write"
name: "Docker Image"
