---
name: CMake
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: ubuntu-latest
          cmake_build_type: RelOnHost
        - platform: macos-latest
          cmake_build_type: RelOnHost
        - platform: windows-latest
          cmake_build_type: Release

    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Generate Buildsystem
      run: >
        cmake -B "${{ runner.workspace }}/bld"
        -D CMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}

    - name: Build
      run: >
        cmake --build "${{ runner.workspace }}/bld"
        --config ${{ matrix.cmake_build_type }}

    - name: Test
      run: >
        ctest --test-dir "${{ runner.workspace }}/bld"
        -C ${{ matrix.cmake_build_type }}
        --timeout 10

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: failure-${{ matrix.platform }}
        path: |
          ${{runner.workspace}}/bld/Testing/
          ${{runner.workspace}}/bld/src/RelOnHost/
          ${{runner.workspace}}/bld/test/*/RelOnHost/
          ${{runner.workspace}}/bld/tool/RelOnHost/


  test_with_old_cmake:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: CMake Version Set
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '2.8.12'

    - name: CMake Version Get
      run: cmake --version

    - name: Create Build Directory
      run: cmake -E make_directory "${{ runner.workspace }}/bld"

    - name: Generate Buildsystem
      shell: bash
      working-directory: "${{ runner.workspace }}/bld"
      # The current convention is to use the -S and -B options
      # to specify source and build directories,
      # but those are only available with CMake 3.13 and higher.
      run: cmake -D CMAKE_BUILD_TYPE=RelOnHost "$GITHUB_WORKSPACE"

    - name: Build
      working-directory: "${{ runner.workspace }}/bld"
      run: cmake --build . --config RelOnHost

    - name: Test
      working-directory: "${{ runner.workspace }}/bld"
      run: ctest --timeout 10 -C RelOnHost


  alpine:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - alpine_arch: x86

    steps:
    - uses: actions/checkout@v4

    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1
      with:
        arch: ${{ matrix.alpine_arch }}
        packages: >
          build-base
          cmake

    - name: Generate Buildsystem
      shell: alpine.sh {0}
      run: cmake -B "bld"

    - name: Build
      shell: alpine.sh {0}
      run: cmake --build "bld"

    - name: Test
      shell: alpine.sh {0}
      run: ctest --test-dir "bld" --timeout 10
